version: "3.8"

services:
  nginx:
    restart: always
    build: ./nginx
    env_file:
      - ./.env.prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/var/www/html/
    networks:
      app:
    depends_on:
      - backend
  backend:
    build: ./backend
    environment:
      - PASTPATH_DB_PORT=5436
      - PORT=8080
    env_file:
      - ./.env.prod
    depends_on:
      - db
    networks:
      app:
  db:
    image: postgres:12.6-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db
    command: -p 5436
    networks:
      app:

networks:
  app:

volumes:
  static_volume:
  postgres_data:
