version: "3.8"

services:
  nginx:
    build: ./nginx
    ports:
      - 8080:80
    env_file:
      - ./.env
    volumes:
      - ./nginx/site:/var/www/html/
    depends_on:
      - backend
    networks:
      app_local:
  backend:
    build: ./backend
    command: /start-reload.sh
    ports:
      - 8081:8080
    env_file:
      - ./.env
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      app_local:
  db:
    image: postgres:12.6-alpine
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env.db
    command: -p 5436
    networks:
      app_local:

networks:
  app_local:
